json.id question_session.id
json.user_id question_session.user_id
json.question_id question_session.question_id
json.time_window question_session.time_window
json.status question_session.status
json.start_time question_session.created_at