json.id team.id
json.league team.league.name
json.name team.name
json.abbreviation team.abbreviation
json.image team.image
json.lat team.lat
json.long team.long
json.coordinates team.coordinates
json.division team.division